### ISSUE TITLE
Cannot find module 'grunt'

### ISSUE THREAD

**Issue by HoundstoothSTL** [yatskevich/grunt-bower-task#1]
Has anyone else run into an issue where you run grunt bower:install and get the following:

```
$ grunt bower:install
Loading "bower_task.js" tasks and helpers...ERROR
>> Error: Cannot find module 'grunt'
```

I use grunt a lot and it works in all other instances, I'm just running a bare bones config just to test the bower-task plugin and I keep getting the error above.  I have grunt installed globally, so I tried just installing the grunt package directly in this project (npm install grunt) and then I run the bower task again and get the following:

```
$ grunt bower:install
Running "bower:install" (bower) task

/Users/rwbennet/Sites/templates/test/node_modules/grunt-bower-task/node_modules/bower/node_modules/tmp/lib/tmp.js:219
    throw err;
          ^
TypeError: Object #<Object> has no method 'options'
    at Object.module.exports (/Users/rwbennet/Sites/templates/test/node_modules/grunt-bower-task/tasks/bower_task.js:24:24)
    at Object.task.registerMultiTask.thisTask (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/grunt/task.js:109:15)
    at Object.task.registerTask.thisTask.fn (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/grunt/task.js:58:16)
    at Task.<anonymous> (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/util/task.js:343:36)
    at Task.start (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/util/task.js:359:5)
    at Object.grunt.tasks (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/grunt.js:143:8)
    at Object.module.exports [as cli] (/Users/rwbennet/Sites/templates/test/node_modules/grunt/lib/grunt/cli.js:36:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/bin/grunt:19:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

Not sure what's going on.  I attached a screenshot of my config.  Any ideas?

![grunt-test](https://f.cloud.github.com/assets/1330601/55519/77fb949c-5ad1-11e2-872a-ea769df4716a.png)

**Comment by yatskevich** [comment]
Could you please tell me what version of grunt do you use? Or just post your `package.json`.

**Comment by HoundstoothSTL** [comment]
grunt v0.3.17

My package.json is extremely simple, just pulling in the grunt-bower-task dependency:

```
{
  "name": "bolt",
  "description": "Bolt starter theme for Houndstooth development",
  "version": "1.0.0",
  "author": "Houndstooth (http://madebyhoundstooth.com/)",
  "homepage": "http://madebyhoundstooth.com/bolt",
  "repository": {
    "type": "git",
    "url": "https://github.com/HoundstoothSTL/bolt.git"
  },
  "bugs": {
    "url": "https://github.com/HoundstoothSTL/bolt/issues"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/HoundstoothSTL/bolt/blob/master/LICENSE"
    }
  ],
  "dependencies": {},
  "devDependencies": {
    "grunt-bower-task": "~0.1.0"
  }
}
```

**Comment by yatskevich** [comment]
`grunt-bower-task` is written for grunt v0.4+, so make sure to use at least version `0.4.0a`

``` json
{ 
  "devDependencies": {
    "grunt": "0.4.0a"
  }
}
```

Also you'll need to `npm install -g grunt-cli`. Read more at [grunt 0.4+ Getting Started](https://github.com/gruntjs/grunt/wiki/Getting-started)

If this solves your problem then I'll close the issue. OK?

**Comment by HoundstoothSTL** [comment]
Ah, didn't realize it was 0.4.x dependent.  Got it working now, thanks!
