### ISSUE TITLE
Fatal error: spawn ENOENT

### ISSUE THREAD

**Issue by adelamarre** [yatskevich/grunt-bower-task#117]
Hi, i have spent a lot of time to find a solution but the error still persists.
I try to completly reinstall nodejs, bower, grunt, try to clean the cahe...nothing.
Environment : 
- EC2, ubuntu 14.04, 
- java version "1.7.0_55"
     OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
     OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
- nodejs : 0.10.25
- bower : 1.3.4
- grunt-cli : 0.1.13
- grunt : 0.4.5 

I have installed grunt-cli, grunt and bower in global (-g).

There is other tasks in my Gruntfile that goes without any error but the bower task fail with this error without any real description of what was wrong...

```
Running tasks: bower:install

Running "bower:install" (bower) task
[D] Task source: /var/lib/jenkins/workspace/WebFrontEndBuild/node_modules/grunt-bower-task/tasks/bower_task.js
Verifying property bower.install exists in config...OK
File: [no files]
Options: cleanTargetDir=false, cleanBowerDir=false, targetDir="app/bower_components", layout="byComponent", install, verbose, copy=false, bowerOptions={}
Fatal error: spawn ENOENT
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

Gruntfile.coffee...

```
...
bower:
      install:
        options:
          targetDir: path + '/bower_components',
          cleanTargetDir: false,
          layout: 'byComponent',
          install: true,
          copy: false,
          verbose: true
```

but bower work fine if i start it manually...

```
bower install
```

I can not find any solution on google so i hope you could help me ;)
Thanks

**Comment by traviskaufman** [comment]
+1 having this same issue when trying to install jasmine

**Comment by ktilcu** [comment]
resolved with new version of grunt-bower-task?
