### ISSUE TITLE
Copy fails with custom git repos

### ISSUE THREAD

**Issue by lrvick** [yatskevich/grunt-bower-task#23]
For some reason it only seems to fail with the 'Overthrow' repo but not the 'ua-parser-js' repo. Not really sure how they differ that is causing grunt-bower-task to break. Regular 'bower install' on the CLI works as expected.
## .bowerrc:

```
{
    "directory": "app/lib"
}
```
## Gruntfile.coffee:

```
...
bower:
    install:
        options:
            targetDir: './app/lib'
            verbose: true
            install: true
            cleanup: true
...
```
## component.json:

```
{
    "name": "myapp",
    "version": "5.0.0",
    "dependencies": {
        "ua-parser-js": "git://github.com/faisalman/ua-parser-js.git",
        "angular": "~1.0.5",
        "angular-resource": "~1.0.5",
        "angular-loader": "~1.0.5",
        "almond": "~0.2.5",
        "normalize-css": "~2.1.1",
        "Overthrow": "git://github.com/filamentgroup/Overthrow.git"
    }
}
```
## Log output

``` text
Running "bower:install" (bower) task
[notice] cleaning up Bower packages
[notice] cleaning up /home/lrvick/Sources/myapp/app/lib
bower cloning git://github.com/faisalman/ua-parser-js.git
bower cloning git://github.com/filamentgroup/Overthrow.git
bower cached git://github.com/faisalman/ua-parser-js.git
bower fetching ua-parser-js
bower cached git://github.com/filamentgroup/Overthrow.git
bower fetching Overthrow
bower cloning git://github.com/angular/bower-angular-loader.git
bower cached git://github.com/angular/bower-angular-loader.git
bower fetching angular-loader
bower cloning git://github.com/angular/bower-angular-resource.git
bower cached git://github.com/angular/bower-angular-resource.git
bower fetching angular-resource
bower cloning git://github.com/angular/bower-angular.git
bower cached git://github.com/angular/bower-angular.git
bower fetching angular
bower cloning git://github.com/jrburke/almond.git
bower cached git://github.com/jrburke/almond.git
bower fetching almond
bower cloning git://github.com/necolas/normalize.css.git
bower cached git://github.com/necolas/normalize.css.git
bower fetching normalize-css
bower checking out angular#v1.0.6
bower checking out Overthrow#a9b67fc3fface4b8bcfdcd04afddcf32ec8f31f8
bower copying /home/lrvick/.bower/cache/angular/683afc7e2aea6bbad5baa3ce1e59216d
bower copying /home/lrvick/.bower/cache/Overthrow/5881f42920a8f8e89b7665c9570cfccf
bower checking out angular-loader#v1.0.6
bower checking out almond#0.2.5
bower copying /home/lrvick/.bower/cache/angular-loader/3e2f57c55f6b3da22fef32ea9dc4be6f
bower copying /home/lrvick/.bower/cache/almond/60b960607ded4c8e1353bcc1ed881a9e
bower checking out angular-resource#v1.0.6
bower checking out normalize-css#v2.1.1
bower checking out ua-parser-js#v0.6.0
bower copying /home/lrvick/.bower/cache/angular-resource/8af0e3f889969e27f60f8957c51eb157
bower copying /home/lrvick/.bower/cache/normalize-css/71749c4026739d2551e50a1081bd0936
bower copying /home/lrvick/.bower/cache/ua-parser-js/25e984f1295a73e7175510e1b4345748
bower cloning git://github.com/angular/bower-angular.git
bower cached git://github.com/angular/bower-angular.git
bower fetching angular
bower checking out angular#v1.0.6
bower copying /home/lrvick/.bower/cache/angular/683afc7e2aea6bbad5baa3ce1e59216d
bower installing ua-parser-js#0.6.0
bower installing angular#1.0.6
bower installing angular-resource#1.0.6
bower installing angular-loader#1.0.6
bower installing almond#0.2.5
bower installing normalize-css#2.1.1
bower installing Overthrow#a9b67fc3fface4b8bcfdcd04afddcf32ec8f31f8
Fatal error: ENOENT, no such file or directory 'app/lib/Overthrow'
```

**Comment by fantactuka** [comment]
I were able install your dependencies list. You can try to clean bower cache before (~/.bower)

```
{
  "name": "collab-app",
  "version": "0.0.1",
  "dependencies": {
    "ua-parser-js": "git://github.com/faisalman/ua-parser-js.git",
    "angular": "~1.0.5",
    "angular-resource": "~1.0.5",
    "angular-loader": "~1.0.5",
    "almond": "~0.2.5",
    "normalize-css": "~2.1.1",
    "Overthrow": "git://github.com/filamentgroup/Overthrow.git"
  }
```

**Comment by giannif** [comment]
I'm having the same problem. If a project dependency lacks a component.json/bower.json, then grunt bower:install fails.

The root project has this as its bower.json:

``` javascript
 "dependencies": {
    "Overthrow": "git://github.com/filamentgroup/Overthrow.git"
  }
```

Running bower directly works:
`bower install`

And this doesn't:
`grunt bower:install` 

If the package has a component.json, such as git://github.com/faisalman/ua-parser-js.git, then `grunt bower:install` works.

**Comment by fantactuka** [comment]
@giannif @lrvick does that still relevant? Grunt-bower-task does not directly rely on component/bower.json. Also can't reproduce it locally on clean install, so it would be very helpful if you provide full stack trace

Thanks!

**Comment by lrvick** [comment]
This is still an active issue. I created a test case to help you debug.

To reproduce issue:

``` bash
git clone https://gist.github.com/5808001.git grunt-bower-task-testcase
cd grunt-bower-task-testcase
npm install
grunt build
```

**Comment by lrvick** [comment]
Stack Trace:

``` bash
Running "bower:install" (bower) task
>> Cleaned target dir /home/lrvick/Sources/grunt-bower-task-testcase/app/lib
bower cloning git://github.com/filamentgroup/Overthrow.git

bower cached git://github.com/filamentgroup/Overthrow.git

bower fetching Overthrow

bower checking out Overthrow#a9b67fc3fface4b8bcfdcd04afddcf32ec8f31f8

bower copying /home/lrvick/.bower/cache/Overthrow/6f6bc66fd370920d9010f2a28b285e14

bower installing Overthrow#a9b67fc3fface4b8bcfdcd04afddcf32ec8f31f8

>> Installed bower packages

/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/bower/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
Error: ENOENT, no such file or directory 'app/lib/Overthrow'
    at Object.fs.statSync (fs.js:524:18)
    at Object.exports.copyDirSyncRecursive (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/wrench/lib/wrench.js:174:23)
    at Copier.copyAssets (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/tasks/lib/asset_copier.js:49:16)
    at data.arrayLoop (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:601:21)
    at Function.eval (eval at createIterator (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:645:19))
    at lodash.(anonymous function) [as each] (/home/lrvick/accesso/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:3642:27)
    at Copier.copyAssets (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/tasks/lib/asset_copier.js:38:16)
    at data.arrayLoop (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:601:21)
    at Function.eval (eval at createIterator (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:645:19))
    at lodash.(anonymous function) [as each] (/home/lrvick/Sources/grunt-bower-task-testcase/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:3642:27)

```

**Comment by fantactuka** [comment]
I see now. 

Please see this comment: https://github.com/yatskevich/grunt-bower-task/issues/38#issuecomment-19132722
For your use case I'd recommend following:

.bowerrc

``` json
{
  "directory": "components"
}
```

task options:

``` js
{
  targetDir: './app/lib',
  verbose: true,
  install: true,
  cleanup: true
}
```

It will install components into `./components`, copy them per `exportsOverride` rules into `./app/lib`, remove `./components` dir.
