### ISSUE TITLE
.bowerrc file conflicts with targetDir location 

### ISSUE THREAD

**Issue by jdivock** [yatskevich/grunt-bower-task#38]
This is on a win x64 machine using git-bash, node 10.9, and grunt-bower-task 0.2.4

Here's the snippet from bower.json

```
  "dependencies": {
    "text": "~2.0.6"
  },
```

Here's the target

```
bower: {
            install: {
                options: {
                    install: true,
                    targetDir: 'webapp/V3RS10N/components/'
                }
            }
        }
```

If I change it to this it works fine however

```
bower: {
            install: {
                options: {
                    install: true,
                    targetDir: 'webapp/V3RS10N/'
                }
            }
        }
```

Here's the error

```
c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node
_modules\bower\node_modules\tmp\lib\tmp.js:260
  throw err;
        ^
Error: ENOENT, no such file or directory 'c:\Users\jdivock\workspace\arch-test\src\main\webapp\V3RS10N\components\text'
    at Object.fs.statSync (fs.js:684:18)
    at Object.exports.copyDirSyncRecursive (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-ask\node_modules\wrench\lib\wrench.js:174:23)
    at null.<anonymous> (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\tasks\lib\asset_copier.js:49:16)
    at c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:601:21
    at Function.eval (eval at createIterator (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:645:19),
 <anonymous>:10:9)
    at lodash.(anonymous function) [as each] (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:3642:27)

    at null.<anonymous> (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\tasks\lib\asset_copier.js:38:16)
    at c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:601:21
    at Function.eval (eval at createIterator (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:645:19), <anonymous>:25:9)
    at lodash.(anonymous function) [as each] (c:\Users\jdivock\workspace\arch-test\src\main\node_modules\grunt-bower-task\node_modules\lodash\lodash.js:3642:27)
```

**Comment by fantactuka** [comment]
On a clean install of the latest version `0.2.3` i was able to run it successfully:

``` js
module.exports = function(grunt) {
  grunt.initConfig({
    bower: {
      install: {
        options: {
          targetDir: 'webapp/V3RS10N/components/and/many/more/levels/deep',
          install: true
        }
      }
    }  
  });

  grunt.loadNpmTasks('grunt-bower-task');
};
```

Can you try to create clean installation with only one task to check if that works for you?

**Comment by jdivock** [comment]
I located the culprit. If there's a .bowerrc file in the same directory that blows it up.

I had this guy sitting at the same level as the Gruntfile

.bowerrc

```
{
    "directory": "webapp/V3RS10N/components"
}
```

If you could resolve this, that'd be good as I need the grunt-bower-task to give devs an initial package on build, but would like to allow them to install additional packages using bower cli. Thanks.

**Comment by fantactuka** [comment]
In case you don't use `exportsOverride` functionality, you might go with following setup:

``` js
  grunt.initConfig({
    bower: {
      install: {
        options: {
          install: true,
          copy: false
        }
      }
    }  
```

**Comment by fantactuka** [comment]
Also consider, that `"directory": "webapp/V3RS10N/components"` in `.bowerrc` and `targetDir: "webapp/V3RS10N/components"` in `Gruntfile.js` is not the same.

When you do `bower install jquery` it installs jquery into dir that set up in `.bowerrc` (`components` by default). 
When you do `grunt bower:install`:
- it runs bower install
- copies installed components from installation dir (which specified in `.bowerrc`) into `targetDir` from `Gruntfile.js`

**Comment by jdivock** [comment]
That did it, thanks!
