### ISSUE TITLE
Installing bootstrap fails with default options?

### ISSUE THREAD

**Issue by srour** [yatskevich/grunt-bower-task#50]
I'm just running 'grunt' with bower configured as the default and i get the following error:

/Users/srour/friendations/node_modules/grunt-bower-task/node_modules/bower/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
Error: ENOENT, no such file or directory 'components/bootstrap/docs/assets/js/bootstrap.js'
    at Object.fs.statSync (fs.js:684:18)
    at null.<anonymous> (/Users/srour/friendations/node_modules/grunt-bower-task/tasks/lib/asset_copier.js:41:23)
    at /Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:601:21
    at Function.eval (eval at createIterator (/Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:1:0), <anonymous>:10:9)
    at lodash.(anonymous function) [as each](/Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:3642:27)
    at null.<anonymous> (/Users/srour/friendations/node_modules/grunt-bower-task/tasks/lib/asset_copier.js:38:16)
    at /Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:601:21
    at Function.eval (eval at createIterator (/Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:1:0), <anonymous>:25:9)
    at lodash.(anonymous function) [as each](/Users/srour/friendations/node_modules/grunt-bower-task/node_modules/lodash/lodash.js:3642:27)
    at Copier.copyAssets (/Users/srour/friendations/node_modules/grunt-bower-task/tasks/lib/asset_copier.js:37:13)

Grunt file:

bower: {
      install: {
       //just run 'grunt bower:install' and you'll see files from your Bower packages in lib directory
      }
    }

bower.json:
{
  "name": "favens-client",
  "version": "0.1.0",
  "ignore": [
    "*_/._",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular-grid": "git://github.com/angular-ui/ng-grid.git#~2.0.7",
    "angular-ui-bootstrap-bower": "git://github.com/angular-ui/bootstrap-bower.git#~0.4.0",
    "angular-ui": "git://github.com/angular-ui/angular-ui.git#~0.4.0",
    "async": "git://github.com/caolan/async.git#~0.2.5",
    "angular-underscore": "git://github.com/floydsoft/angular-underscore.git",
    "bootstrap": "git://github.com/twbs/bootstrap.git#~3.0.0-rc1",
    "node-uuid": "git://github.com/broofa/node-uuid.git#~1.4.0",
    "font-awesome": "git://github.com/FortAwesome/Font-Awesome.git#~3.2.1",
    "jquery-ui": "git://github.com/components/jqueryui.git#~1.10.3",
    "select2": "git://github.com/ivaynberg/select2.git#~3.4.1",
    "underscore": "git://github.com/documentcloud/underscore.git#~1.5.1"
  }
}

**Comment by yosuke-furukawa** [comment]
I got this same error, but that is not grunt-bower-task's fault.
bootstrap changed their folders, bootstrap developers need to fix their main property in their **bower.json**.

https://github.com/twbs/bootstrap/issues/8799?source=c
According to the issue, they fixed the problem. but they cannot publish the latest libraries.

If you would like to fix this problem soon, you would rewrite main property.
Or you would drop your bootstrap version.
